version: '3.9'


services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

    ports:
      - 8000:8000
    volumes:
      - ./project_code:/project_code
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=projectsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=dbuser
      - DB_PASSWORD=dbpassword

    depends_on:
      - db


  db:
    image: postgres:13-alpine
    environment: 
      - POSTGRES_DB=devdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword


