# Generated by Django 4.1 on 2023-01-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
